### ISSUE TITLE
How to call npm ["ci"]?

### ISSUE THREAD

**Issue by bahmutov** [actions/toolkit#209]
I am trying to run `exec.exec` that installs NPM modules `npm ci` command. When I do

```js
const exec = require('@actions/exec')
// "@actions/exec": "1.0.1",
exec.exec('npm ci')
```

then the install goes through

If I try to use command + arguments form

```js
exec.exec('npm', ['ci'])
```
then I get an error:
```
Error: There was an error when attempting to execute the process 'npm'. This may indicate the process failed to start. Error: spawn npm ENOENT
    at ExecState._setResult (/home/runner/work/testing-actions/testing-actions/actions/cypress/node_modules/@actions/exec/lib/toolrunner.js:545:25)
    at ExecState.CheckComplete (/home/runner/work/testing-actions/testing-actions/actions/cypress/node_modules/@actions/exec/lib/toolrunner.js:531:18)
    at ChildProcess.<anonymous> (/home/runner/work/testing-actions/testing-actions/actions/cypress/node_modules/@actions/exec/lib/toolrunner.js:418:27)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by bryanmacfarlane** [comment]
You need to call io.which and you also need to use await on the exec call.

See tests for all the variations:
https://github.com/actions/toolkit/blob/master/packages/exec/__tests__/exec.test.ts#L77

**Comment by ericsciple** [comment]
@bahmutov check if npm is in your PATH.

Try this script locally (npm and node are both in my PATH):

```bash
mkdir test-exec
cd test-exec
npm install @actions/exec ./
node -e "var exec = require('@actions/exec'); exec.exec('npm', ['--version']);"
```

**Comment by bahmutov** [comment]
perfect - using `io.which` and then `exec.exec` works

**Comment by ericsciple** [comment]
@bahmutov thanks for confirmation. Did you run into the issue on Linux or Windows?

On Windows I'm consistently seeing the ENOENT failure when using both `exec('npm --version')` and `exec('npm', ['--version'])`

But not on Linux.

**Comment by bahmutov** [comment]
The problem right now is on Windows, Linux and Darwin seem pretty happy

**Comment by ericsciple** [comment]
@bahmutov thanks for confirming. I'll go ahead and close this issue again (`io.which` is the workaround). I'll open a separate issue - cmd/bat file on Windows doesnt resolve from PATH

**Comment by ericsciple** [comment]
https://github.com/actions/toolkit/issues/218
