### ISSUE TITLE
Tool not found in path

### ISSUE THREAD

**Issue by alexkappa** [actions/toolkit#243]
Hi, 

I'm not sure if this is a bug or a mistake on my part but I've been scratching my head over this for a while and can't figure out what is wrong...

```
const tool = 'cc-test-reporter';

module.exports.download = async function (options = {}) {

  options.version = options.version || 'latest';

  let toolPath = tc.find(tool, options.version);
  if (!toolPath) {
    const url = getUrl(options);
    const downloadPath = await tc.downloadTool(url);
    toolPath = path.join(path.dirname(downloadPath), tool);
    await io.mv(downloadPath, toolPath);
    await exec.exec(`chmod +x ${toolPath}`);

    toolPath = await tc.cacheDir(path.dirname(toolPath), tool, options.version);
  }

  core.addPath(toolPath);
  await exec.exec(tool);
}
```

When running the tests it seems that the tool is not found in the PATH, however the debug logs clearly show the PATH is prepended  correctly. 

Here's the console output.

```
::debug::isExplicit:
::debug::explicit? false
::debug::isExplicit:
::debug::explicit? false
::debug::evaluating 0 versions
::debug::match not found
::debug::Downloading https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64
::debug::Downloading /Users/alexkappa/Code/js/codeclimate-test-reporter/runner/temp/8ed25d72-9087-4853-a606-e1dd9a564ee3
 FAIL  ./index.test.js
  ● execute a command using the reporter

    There was an error when attempting to execute the process 'cc-test-reporter'. This may indicate the process failed to start. Error: spawn cc-test-reporter ENOENT

      at ExecState._setResult (node_modules/@actions/exec/src/toolrunner.ts:620:17)
      at ExecState.CheckComplete (node_modules/@actions/exec/src/toolrunner.ts:605:12)
      at ChildProcess.<anonymous> (node_modules/@actions/exec/src/toolrunner.ts:471:15)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        4.987s, estimated 5s
Ran all test suites.
::debug::download complete
[command]chmod +x /Users/alexkappa/Code/js/codeclimate-test-reporter/runner/temp/cc-test-reporter
::debug::Caching tool cc-test-reporter latest x64
::debug::source dir: /Users/alexkappa/Code/js/codeclimate-test-reporter/runner/temp
::debug::destination /Users/alexkappa/Code/js/codeclimate-test-reporter/runner/cache/cc-test-reporter/latest/x64
::debug::finished caching tool
::add-path::/Users/alexkappa/Code/js/codeclimate-test-reporter/runner/cache/cc-test-reporter/latest/x64
[command]cc-test-reporter
```

Any help is greatly appreciated!

**Comment by ericsciple** [comment]
@alexkappa is it a .cmd or .bat file. If so refer to issue https://github.com/actions/toolkit/issues/218 for a workaround

**Comment by alexkappa** [comment]
No I'm running it on macOS. I managed to get it working with [this code](https://github.com/aktions/codeclimate-test-reporter/blob/24c5491864d13038aa7d8c5e7de7b9149ace4112/codeclimate.js). It must have been an error on my part.

I do still have some issues with caching on mac but I'll continue debugging and file a separate issue if it persists.

Many thanks!
