### ISSUE TITLE
setOutput with Boolean Throws Strange Error

### ISSUE THREAD

**Issue by fishcharlie** [actions/toolkit#416]
**Describe the bug**

When running `core.setOutput("isValid", true)` I get an internal error.

**To Reproduce**
1. Run `core.setOutput("isValid", true)`

**Expected behavior**

It to throw a more descriptive error or not error at all.

**Current behavior**

```
/home/runner/work/dynamoose/dynamoose/publish/node_modules/@actions/core/lib/command.js:66
5
        .replace(/%/g, '%25')
6
         ^
7

8
TypeError: (s || "").replace is not a function
9
    at escapeData (/home/runner/work/dynamoose/dynamoose/publish/node_modules/@actions/core/lib/command.js:66:10)
10
    at Command.toString (/home/runner/work/dynamoose/dynamoose/publish/node_modules/@actions/core/lib/command.js:60:35)
11
    at Object.issueCommand (/home/runner/work/dynamoose/dynamoose/publish/node_modules/@actions/core/lib/command.js:23:30)
12
    at Object.setOutput (/home/runner/work/dynamoose/dynamoose/publish/node_modules/@actions/core/lib/core.js:88:15)
13
    at /home/runner/work/dynamoose/dynamoose/publish/information/index.js:8:7
14
    at Array.forEach (<anonymous>)
15
    at Object.<anonymous> (/home/runner/work/dynamoose/dynamoose/publish/information/index.js:6:21)
16
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
17
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
18
    at Module.load (internal/modules/cjs/loader.js:1002:32)
19
```

PS, can you also **please** fix GitHub Actions to not copy line numbers when copying logs (as seen above)? 🤦‍♂️ 🙏 

**Desktop (please complete the following information):**

GitHub Actions

**Additional context**

NA

**Comment by thboop** [comment]
Hey @fishcharlie , this should be resolved in `@actions/core 1.2.4` released today. I'm going to close this for now, but if you are still seeing this issue let me know and we can reopen!.
