### ISSUE TITLE
Cache Stuck

### ISSUE THREAD

**Issue by ScottPierce** [actions/toolkit#658]
**Describe the bug**
All my actions are running, but are refusing to cache with the same error:
```
Post job cleanup.
Unable to reserve cache with key Linux-modules-0c1e633988f0463573ae79cec4e4e741153037a6a270a901c8bf040b3d674a4f, another job may be creating this cache.
```

There must be some sort of race condition, and the cache is stuck, because they all have the same precache log:
```
Run actions/cache@v2
  with:
    path: **/node_modules
    key: Linux-modules-0c1e633988f0463573ae79cec4e4e741153037a6a270a901c8bf040b3d674a4f
Cache not found for input keys: Linux-modules-0c1e633988f0463573ae79cec4e4e741153037a6a270a901c8bf040b3d674a4f
```

I imagine that if I changed my yarn lock file, which the cache is based on, this issue would resolve itself.

**Expected behavior**
That the cache always works, and when it gets stuck like this, it would automatically fix itself.

**Additional context**
I don't know how to reproduce this. Normally the cache works. There just is clearly some sort of race condition where it can get stuck.

**Comment by Pentarctagon** [comment]
I've run into the same issue.  Each time it starts with `Cache not found for input keys: windows-master-N002` and ends with `Unable to reserve cache with key windows-master-N002, another job may be creating this cache.`, so no cache ends up actually getting created.

**Comment by rcowsill** [comment]
I'm getting this too, on a GitHub-hosted runner. Logs are here: https://github.com/rcowsill/NodeGoat/runs/1504051837 (see the `Post Use cache (docker layers)` section)

In my case it's happening when the cache with the matching key already exists. Normally that would fail with the message "Cache already exists." instead of "Unable to reserve cache with key [...]"

I'm using [satackey/action-docker-layer-caching@v0.0.8](https://github.com/satackey/action-docker-layer-caching), which imports @actions/cache@1.0.4. In case it's important, that action is running up to four cache uploads in parallel, but all caches have unique keys within a single build. I was only running that one build using those cache keys at the time.

**Comment by ScottPierce** [comment]
I've seen this happen again. This might be the initial error:

```
Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
```

**Comment by ScottPierce** [comment]
I've also noticed this is extremely reproducible for some reason. This failure happens a lot for my docker runners when things are in parallel, especially now that I have 8 runners now.

**Comment by ScottPierce** [comment]
This is now blocking the build system. I'm seeing this build error constantly:
```
Warning: uploadChunk (start: 100663296, end: 134217727) failed: Cache service responded with 503
/_work/_actions/actions/cache/v2/dist/save/index.js:3305
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/_work/_actions/actions/cache/v2/dist/save/index.js:3305:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by tmcw** [comment]
I'm hitting the same issue - getting

```
UnhandledPromiseRejectionWarning: ReserveCacheError: Unable to reserve cache with key linkrot-v2-, another job may be creating this cache.
```

Always when using `@actions/cache` to persist a cache. My implementation is as vanilla as possible, I think: https://github.com/tmcw/linkrot/blob/main/action.ts#L37-L46

After saving the cache once, it can't be saved again and I always get this `ReserveCacheError`.

**Comment by klausbadelt** [comment]
Same issue, macOS runner. Works on GitHub runner, but not local. Our key is `key: ${{ runner.os }}-yarn-${{ hashFiles('web/yarn.lock') }}`.
```
Unable to reserve cache with key macOS-yarn-5967645e7e3b673f1a9f0792c61e21863dc66df3a592de7561b991f867052c7b, another job may be creating this cache
```

**Comment by christianchown-santander** [comment]
I think we encountered this problem by manually cancelling a run that had begun caching with a certain key before it completed the caching step. It seemed to never released the key, and subsequent runs that try to use the same key fail to reserve it:

> Run actions/cache@v2 
> Cache not found for input keys: \<key>

...

> Post Run actions/cache@v2
> Post job cleanup. 
> Unable to reserve cache with key \<key>, another job may be creating this cache.

Our only workaround was to change the key.

**Comment by bilelmoussaoui** [comment]
I'm also experiencing this issue with my custom github action, it seems that it really insists on the cache key being "unique"? otherwise it keeps failing with `Error: Failed to save cache: ReserveCacheError: Unable to reserve cache with key flatpak-builder-0f51bddf4f15c39e39b55b6c92c8249d99d44205, another job may be creating this cache.` Except there are 0 other jobs running at the same time. The issue can be triggered by re-running a workflow job that just created the cache.

**Comment by RSickenberg** [comment]
Same here, or some `Warning: uploadChunk (start: 67108864, end: 100663295) failed: Cache service responded with 503`

**Comment by rafis** [comment]
```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/***/*** --files-from manifest.txt
Warning: uploadChunk (start: 33554432, end: 67108863) failed: Cache service responded with 503
/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:4043
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:4043:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by Mubelotix** [comment]
I had a **relative path** in the list of files to cache. But it seems that relative paths are not supported. **Removing it fixed** the error.

**Comment by btrepp** [comment]
I think I am hitting this on two workflows, as rust-cache uses this underneath.
Is there any way to view/delete the caches if they are in a 'funky' state?

Manually overriding cache keys, and doing a commit seems like a bit of whack-a-mole approach. Happy to manually delete the cache from a UI (or API) feels like a bit of a cleaner workaround until the root cause is fixed.

**Comment by MichaelTamm** [comment]
I also experienced Warning: uploadChunk (start: 67108864, end: 100663295) failed: Cache service responded with 503

**Comment by mabdullahadeel** [comment]
Faced the same on `macOS` matrix.

```
Error: uploadChunk (start: 0, end: 15553027) failed: Cache service responded with 503
```
**Though everything worked on the very next run.**

**Comment by swalkinshaw** [comment]
I ran into this issue and _think_ I figured out the most common cause. It seems like there's two causes for this:

1. Transient uploading issues (bad file descriptor, chunk, 503s, etc)
2. trying to save the cache for a cache key that was already saved (and restored)

If you're running into this problem and **don't** have any errors uploading, I'm guessing the root cause is the last one.

Basically I compared what this cache library was doing with how the official `actions/cache` action actually uses it and here's the key part: https://github.com/actions/cache/blob/611465405cc89ab98caca2c42504d9289fb5f22e/src/save.ts#L39-L54

The official action does not try to save the cache if there was previously an exact key match on a cache hit. If you just naively do a restore cache + save cache (like I tried), you'll run into this error every time there's a cache hit (meaning you're trying to save a cache key which is already cached).

So unfortunately the solution is to replicate all the logic within https://github.com/actions/cache/blob/611465405cc89ab98caca2c42504d9289fb5f22e/src/save.ts.

Here's a utility function to wrap a cacheable function (like calling `exec.exec('some command')`) which works for me:

```js
async function withCache(cacheable, paths, baseKey, hashPattern) {
  const keyPrefix = `${process.env.RUNNER_OS}-${baseKey}-`;
  const hash = await glob.hashFiles(hashPattern);
  const primaryKey = `${keyPrefix}${hash}`;
  const restoreKeys = [keyPrefix];

  const cacheKey = await cache.restoreCache(paths, primaryKey, restoreKeys);

  if (!cacheKey) {
    core.info(`Cache not found for keys: ${[primaryKey, ...restoreKeys].join(", ")}`);
    return;
  }

  core.info(`Cache restored from key: ${cacheKey}`);

  await cacheable();

  if (isExactCacheKeyMatch(primaryKey, cacheKey)) {
    core.info(`Cache hit occurred on the primary key ${primaryKey}, not saving cache.`);
    return;
  }

  await cache.saveCache(paths, primaryKey);
}

await withCache(async () => {
  await exec.exec('npm install')
}, ['node_modules], 'npm', '**/package.json');
```

You might want to customize the arguments and how the keys are built (maybe accept a list of restore keys too).

**Comment by filipworksdev** [comment]
A build fails with  `Unable to reserve cache with key 3.1.10-x64-master, another job may be creating this cache.` First time I have seen this about 1-2 weeks ago on different repo. Now I see it at least once in every repo per week.

**Comment by filipworksdev** [comment]
A build fails with `Unable to reserve cache with key 3.1.10-x64-master, another job may be creating this cache`. First time I have seen this about 1-2 weeks ago on different repo. Now I see it at least once in every repo per week.

**Comment by Francesco146** [comment]
the issue is still reproducible, there's not a workaround at the moment

**Comment by natemcintosh** [comment]
Had a similar issue with ruff:
```sh
ruff failed
  Cause: Failed to create cache file '/home/runner/work/aoc_2023/aoc_2023/.ruff_cache/0.1.12/1323824952410372998'
  Cause: No such file or directory (os error 2)
```
Emptying the workflow file, committing, then pasting it back in fixed the issue.

**Comment by Alfmac22** [comment]
ruff failed
  Cause: Failed to create cache file '/home/runner/work/aoc_2023/aoc_2023/.ruff_cache/0.1.12/1323824952410372998'
  Cause: No such file or directory (os error 2)

**Comment by kristof-mattei** [comment]
Having this issue today.

Ghost cache:

![image](https://github.com/actions/toolkit/assets/864376/d32f3111-7ea4-41f1-9c21-c77ab4d8e3d0)

GH API:

```
kristof in xxx on  main is 📦 v1.0.1 via  v21.6.2 took 3s
❯ gh cache list

Showing 1 of 2 caches in kristof-mattei/5482974a16f5ed7ad344dcdd9bff31647214a4de871ef61fa42619d11fb6cf65

ID    KEY                                                                                    SIZE       CREATED              ACCESSED
1133  node-cache-Linux-npm-xxxx  27.84 MiB  about 2 minutes ago  about 2 minutes ago
```

Logs:

```
2024-02-29T19:05:58.8571189Z [command]/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/REDACTED/REDACTED --files-from manifest.txt --use-compress-program zstdmt
2024-02-29T19:05:59.1240788Z Failed to save: Unable to reserve cache with key node-cache-Linux-npm-a60ac0f76178055bc94f0972ca353feba863ea267f0825102798f2d1b6ec3b7e, another job may be creating this cache. More details: Cache already exists. Scope: refs/pull/572/merge, Key: node-cache-Linux-npm-a60ac0f76178055bc94f0972ca353feba863ea267f0825102798f2d1b6ec3b7e, Version: 04d00cc68e25ee34fd8b04095d0a46a28244d98af53e6925e47ed311d487b1d6
```

**Comment by AshwinSundar** [comment]
I have also run into this issue recently

If you cancel a run after it has "reserved" a key for a cache, but before it has actually generated the cache as an artifact, subsequent runs will fail with a cryptic message:
 
```
2025-01-16T21:49:39.8189098Z Failed to save: Unable to reserve cache with key 123, another job may be creating this cache. More details: Cache already exists. Scope: refs/pull/001/merge, Key: 123, Version: abc
https://github.com/actions/toolkit/issues/658
```

This puzzled me because there was no cache with this name, and the error continued to occur even after I deleted all caches in GitHub! The solution, as given by https://github.com/actions/toolkit/issues/658#issuecomment-767616351,  was to change the key manually in the workflow by prepending a 2:

```yml
key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
restore-keys: |
    ${{ runner.os }}-yarn2-
```

**Comment by shriyanskapoor** [comment]
> I ran into this issue and _think_ I figured out the most common cause. It seems like there's two causes for this:
> 
> 1. Transient uploading issues (bad file descriptor, chunk, 503s, etc)
> 2. trying to save the cache for a cache key that was already saved (and restored)
> 
> If you're running into this problem and **don't** have any errors uploading, I'm guessing the root cause is the last one.
> 
> Basically I compared what this cache library was doing with how the official `actions/cache` action actually uses it and here's the key part: https://github.com/actions/cache/blob/611465405cc89ab98caca2c42504d9289fb5f22e/src/save.ts#L39-L54
> 
> The official action does not try to save the cache if there was previously an exact key match on a cache hit. If you just naively do a restore cache + save cache (like I tried), you'll run into this error every time there's a cache hit (meaning you're trying to save a cache key which is already cached). Ideally `saveCache` was an atomic operation, but since it's not we have to replicate that behaviour.
> 
> So unfortunately the solution is to replicate all the logic within https://github.com/actions/cache/blob/611465405cc89ab98caca2c42504d9289fb5f22e/src/save.ts.
> 
> Here's a utility function to wrap a cacheable function (like calling `exec.exec('some command')`) which works for me:
> 
> async function withCache(cacheable, paths, baseKey, hashPattern) {
>   const keyPrefix = `${process.env.RUNNER_OS}-${baseKey}-`;
>   const hash = await glob.hashFiles(hashPattern);
>   const primaryKey = `${keyPrefix}${hash}`;
>   const restoreKeys = [keyPrefix];
> 
>   const cacheKey = await cache.restoreCache(paths, primaryKey, restoreKeys);
> 
>   if (!cacheKey) {
>     core.info(`Cache not found for keys: ${[primaryKey, ...restoreKeys].join(", ")}`);
>   }
> 
>   core.info(`Cache restored from key: ${cacheKey}`);
> 
>   await cacheable();
> 
>   if (isExactCacheKeyMatch(primaryKey, cacheKey)) {
>     core.info(`Cache hit occurred on the primary key ${primaryKey}, not saving cache.`);
>     return;
>   }
> 
>   await cache.saveCache(paths, primaryKey);
> }
> 
> await withCache(async () => {
>   await exec.exec('npm install')
> }, ['node_modules], 'npm', '**/package.json');
> You might want to customize the arguments and how the keys are built (maybe accept a list of restore keys too).

This is the only things that worked. 

Basically I was trying to save cache using a key that's reserved and it's pretty pointless to do so. The way it's being done in the action's code is doing it the right way, thanks dude!

**Comment by kristof-mattei** [comment]
> > I ran into this issue and _think_ I figured out the most common cause. It seems like there's two causes for this:
> > 
> > 1. Transient uploading issues (bad file descriptor, chunk, 503s, etc)
> > 2. trying to save the cache for a cache key that was already saved (and restored)
> > 
> > If you're running into this problem and **don't** have any errors uploading, I'm guessing the root cause is the last one.
> > Basically I compared what this cache library was doing with how the official `actions/cache` action actually uses it and here's the key part: https://github.com/actions/cache/blob/611465405cc89ab98caca2c42504d9289fb5f22e/src/save.ts#L39-L54
> > The official action does not try to save the cache if there was previously an exact key match on a cache hit. If you just naively do a restore cache + save cache (like I tried), you'll run into this error every time there's a cache hit (meaning you're trying to save a cache key which is already cached). Ideally `saveCache` was an atomic operation, but since it's not we have to replicate that behaviour.
> > So unfortunately the solution is to replicate all the logic within https://github.com/actions/cache/blob/611465405cc89ab98caca2c42504d9289fb5f22e/src/save.ts.
> > Here's a utility function to wrap a cacheable function (like calling `exec.exec('some command')`) which works for me:
> > async function withCache(cacheable, paths, baseKey, hashPattern) {
> > const keyPrefix = `${process.env.RUNNER_OS}-${baseKey}-`;
> > const hash = await glob.hashFiles(hashPattern);
> > const primaryKey = `${keyPrefix}${hash}`;
> > const restoreKeys = [keyPrefix];
> > const cacheKey = await cache.restoreCache(paths, primaryKey, restoreKeys);
> > if (!cacheKey) {
> > core.info(`Cache not found for keys: ${[primaryKey, ...restoreKeys].join(", ")}`);
> > }
> > core.info(`Cache restored from key: ${cacheKey}`);
> > await cacheable();
> > if (isExactCacheKeyMatch(primaryKey, cacheKey)) {
> > core.info(`Cache hit occurred on the primary key ${primaryKey}, not saving cache.`);
> > return;
> > }
> > await cache.saveCache(paths, primaryKey);
> > }
> > await withCache(async () => {
> > await exec.exec('npm install')
> > }, ['node_modules], 'npm', '**/package.json');
> > You might want to customize the arguments and how the keys are built (maybe accept a list of restore keys too).
> 
> Thanks [@swalkinshaw](https://github.com/swalkinshaw), This is the only things that worked.
> 
> Basically I was trying to save cache using a key that's reserved and it's pretty pointless to do so. The way it's being done in the action's code is doing it the right way, I also adopted it to my code.

I disagree. Quite often we work on stuff where we fetch a cache, do something, and store it all back, with the new work added to it. 

For example one might take a more global NPM cache.

**Comment by Qix-** [comment]
Does this mean caches can't be used to... cache?

I don't really understand the point of caches if you can't update the cache. Or fetch old runs' caches. If the key is supposed to be unique for every single run (otherwise we hit this error message), then how can it possibly restore previous runs' caches?

My usecase is that I'm building LLVM and Rust. That takes ~3 hours on a public, free Actions runner. Caching the build artifacts, even if they're outdated or broken or _whatever_, is still preferable simply because the build system can handle those cases. Getting _anything_ from before is going to improve the 3 hour time.

So are we supposed to be able to use the caching system with a "stable" key, and this is just a transient issue? Or is this really something that isn't supported by the cache system?

**Comment by mabar** [comment]
> Or fetch old runs' caches.

@Qix- That's exactly what you can and should do. `example-` for restoring and `example-${{github.run_id}}` for storing cache is all you need. 

Just use the [save](https://github.com/actions/cache/blob/main/save/README.md) and [restore](https://github.com/actions/cache/blob/main/restore/README.md) actions separately. It will restore matching newest cache from current branch and if not found, from the primary branch.

**Comment by mabar** [comment]
Yeah, the docs are terrible, I got it wrong too (for the first few times)

This is a minimal working example. It saves cache even on failure.
It should be possible to add a condition to save cache when build fails but you are sure the cache was generated, but I never tried that.

```yaml
  - name: "Restore cache"
    uses: actions/cache/restore@v4
    with:
      path: path/to/cache 
      key: "example-${{ github.run_id }}"
      restore-keys: |
        example-

  - name: "Run whatever"
    run: "your/script.sh"

  - name: "Save cache"
    uses: actions/cache/save@v4
    if: always()
    with:
      path: path/to/cache 
      key: "example-${{ github.run_id }}"
```

If you have more parallel builds in matrix, creating a unique key may be a bit of a challenge. Here's the solution I came up with:

```yaml
    - name: "Create cache key"
      uses: "actions/github-script@v7"
      id: "cache-key"
      with:
        script: "return `ori-php-phpstan--job-${{ github.job }}--os-${{ runner.os }}--matrix-${{ toJson(matrix) }}--run`.replaceAll(',', '+').replaceAll(' ', '').replaceAll(/(?:\\r\\n|\\r|\\n)/g, '');"
        result-encoding: "string"
```

And then use `"${{ steps.cache-key.outputs.result }}-"` in `restore-keys` and `"${{ steps.cache-key.outputs.result }}-${{ github.run_id }}"` in `key`

**Comment by Qix-** [comment]
Oh my goodness I've been struggling with the caches for years at this point, thank you so much. Super helpful. :)

**Comment by avaz** [comment]
What I did to make it work was to have a more _wider_ cache key for restoring and always generating a new one for saving. Something like:
```
      - name: Restore cache
        uses: actions/cache/restore@v5
        with:
          path: ./.output/${{ inputs.module }}/${{ matrix.group }}
          key: output-${{ inputs.module }}-${{ github.ref_name }}-${{ matrix.group }}
          restore-keys: |
            test-output-${{ inputs.module }}-${{ github.ref_name }}-${{ matrix.group }}-

...

      - name: Save cache
        if: always()
        uses: actions/cache/save@v5
        with:
          path: ./.output/${{ inputs.module }}/${{ matrix.group }}
          key: output-${{ inputs.module }}-${{ github.ref_name }}-${{ matrix.group }}-${{ github.run_id }}-${{ github.run_attempt }}

```

The secret is the `github.run_attempt` that ensures that always a new key is used for saving so it doesn't conflict with previous restored ones. My understanding is that when restoring the `cache` action restores that latest one if there was more than one match and this should be enough in a retry cycle as the latest one is always the previous one in this setup.
